# GitHub Sponsors configuration
github: ntoledo319

# Alternative funding platforms (optional)
# patreon: yourusername
# open_collective: yourusername
# ko_fi: yourusername
# custom: ["https://your-website.com/donate"]
