#!/usr/bin/env python3
"""
OAuth Environment Setup Helper
Helps set up environment variables for local testing
"""

import os
import secrets
import subprocess
import sys

def generate_session_secret():
    """Generate a secure session secret"""
    return secrets.token_urlsafe(32)

def create_env_file():
    """Create .env file with OAuth configuration"""
    print("🔧 OAuth Environment Setup Helper")
    print("=" * 60)
    
    # Check if .env exists
    if os.path.exists('.env'):
        response = input("\n⚠️  .env file already exists. Overwrite? (y/N): ")
        if response.lower() != 'y':
            print("Cancelled.")
            return
    
    print("\n📝 Enter your Google OAuth credentials:")
    print("(Get these from https://console.cloud.google.com/)")
    
    # Get OAuth credentials
    client_id = input("\nGOOGLE_CLIENT_ID: ").strip()
    if not client_id:
        print("❌ Client ID is required!")
        return
        
    client_secret = input("GOOGLE_CLIENT_SECRET: ").strip()
    if not client_secret:
        print("❌ Client secret is required!")
        return
    
    # Generate session secret
    session_secret = generate_session_secret()
    print(f"\n✅ Generated SESSION_SECRET: {session_secret[:10]}...")
    
    # Database URL
    print("\nDatabase URL (press Enter for default SQLite):")
    db_url = input("DATABASE_URL [sqlite:///nous.db]: ").strip()
    if not db_url:
        db_url = "sqlite:///nous.db"
    
    # Create .env content
    env_content = f"""# NOUS Intelligence OAuth Configuration
# Generated by setup_oauth_local.py

# Google OAuth Credentials
GOOGLE_CLIENT_ID={client_id}
GOOGLE_CLIENT_SECRET={client_secret}

# Security
SESSION_SECRET={session_secret}

# Database
DATABASE_URL={db_url}

# Optional: Development settings
FLASK_DEBUG=true
FLASK_ENV=development
"""
    
    # Write .env file
    with open('.env', 'w') as f:
        f.write(env_content)
    
    print("\n✅ Created .env file successfully!")
    
    # Add to .gitignore
    if os.path.exists('.gitignore'):
        with open('.gitignore', 'r') as f:
            gitignore = f.read()
        
        if '.env' not in gitignore:
            with open('.gitignore', 'a') as f:
                f.write('\n# Environment files\n.env\n')
            print("✅ Added .env to .gitignore")
    
    print("\n📋 Next steps:")
    print("1. Load environment variables:")
    print("   export $(cat .env | xargs)")
    print("\n2. Or use python-dotenv:")
    print("   pip install python-dotenv")
    print("   # Add to app.py: from dotenv import load_dotenv; load_dotenv()")
    
    # Test the configuration
    print("\n🧪 Test your configuration:")
    print("   python3 test_oauth_simple.py")

def export_env_vars():
    """Export environment variables from .env file"""
    if not os.path.exists('.env'):
        print("❌ No .env file found. Run this script first to create one.")
        return
    
    print("\n📤 Exporting environment variables...")
    
    # Read .env file
    with open('.env', 'r') as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith('#') and '=' in line:
                key, value = line.split('=', 1)
                os.environ[key] = value
                print(f"✅ Set {key}")
    
    print("\n✅ Environment variables exported!")
    print("Note: This only affects the current Python process.")
    print("For shell export, run: export $(cat .env | xargs)")

def main():
    """Main function"""
    if len(sys.argv) > 1 and sys.argv[1] == 'export':
        export_env_vars()
    else:
        create_env_file()

if __name__ == "__main__":
    main() 